spring:
    application:
        name: rest
logging:
    level:
        springframework:
            web:
                client:
                    RestTemplate: DEBUG
        org.apache.http: DEBUG
        httpclient.wire: DEBUG
